/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.contenido.BIENES;

import java.awt.event.ActionListener;
import org.contenido.PANEL_INICIO.PanelInicio;
import org.contenido.controlador.Controlador;
import org.contenido.controlador.controladorImpl.BienControlador;
import org.contenido.dto.BienDTO;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;

import org.contenido.controlador.controladorImpl.AmbienteControlador;
import org.contenido.controlador.controladorImpl.CategoriaControlador;
import org.contenido.controlador.controladorImpl.EstadoControlador;
import org.contenido.controlador.controladorImpl.InmuebleControlador;
import org.contenido.dto.AmbienteDTO;
import org.contenido.dto.CategoriaDTO;
import org.contenido.dto.EstadoDTO;
import org.contenido.dto.InmuebleDTO;


/**
 *
 * @author SERT
 */
public class BienesPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form BienesPrincipal
     */
    Controlador<BienDTO> controlador = new BienControlador();
    List<BienDTO> listabien = controlador.listarTodo();
    List<BienDTO> listaFiltradaBien = new ArrayList<>();
    public BienesPrincipal() {
        initComponents();
        
        jComboBox4.removeAllItems();
        CategoriaDTO todosCat = new CategoriaDTO(); 
        todosCat.setId(0); 
        todosCat.setNombre("Todos");
        jComboBox4.addItem(todosCat);
        new CategoriaControlador().listarTodo().forEach(jComboBox4::addItem);
        
        jComboBox1.removeAllItems();
        EstadoDTO todosEst = new EstadoDTO(); 
        todosEst.setId(0); 
        todosEst.setTipo("Todos");
        jComboBox1.addItem(todosEst);
        new EstadoControlador().listarTodo().forEach(jComboBox1::addItem);
        
        jComboBox2.removeAllItems();
        AmbienteDTO todosAmb = new AmbienteDTO(); 
        todosAmb.setId(0); 
        todosAmb.setNombre("Todos");
        jComboBox2.addItem(todosAmb);
        new AmbienteControlador().listarTodo().forEach(jComboBox2::addItem);
        
        jComboBox3.removeAllItems();
        InmuebleDTO todosInm = new InmuebleDTO(); 
        todosInm.setId(0); 
        todosInm.setNombre("Todos");
        jComboBox3.addItem(todosInm);
        new InmuebleControlador().listarTodo().forEach(jComboBox3::addItem);
        
        cargarBien();
        
        DocumentListener dl = new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) { aplicarFiltros(); }
            @Override
            public void removeUpdate(DocumentEvent e){ aplicarFiltros(); }
            @Override
            public void changedUpdate(DocumentEvent e){ aplicarFiltros(); }
        };
        jTextField2.getDocument().addDocumentListener(dl);
        jTextField1.getDocument().addDocumentListener(dl);
        jTextField6.getDocument().addDocumentListener(dl);
        jTextField8.getDocument().addDocumentListener(dl);

        // Cuando cambie cualquiera de los combos:
        ActionListener al = e -> aplicarFiltros();
        jComboBox1.addActionListener(al);
        jComboBox2.addActionListener(al);
        jComboBox3.addActionListener(al);
        jComboBox4.addActionListener(al);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaBien = new org.jdesktop.swingx.JXTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PANEL_INICIO/logo1.jpg"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Control de Bienes");

        jLabel3.setText("Accede al historial completo de los bienes asignados");

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Atrás");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 243, 239));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Añadir bien");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Modificar bien");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TablaBien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Descripción", "Categoría", "Estado", "Responsable a cargo", "Inmueble", "Ambiente", "Fecha de Registro"
            }
        ));
        jScrollPane2.setViewportView(TablaBien);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar según:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Categoría:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Responsable:");

        jButton5.setBackground(new java.awt.Color(255, 153, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Exportar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ambiente:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Fecha de registro:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Inmueble:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Código:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 73, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel7)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AñadirRegistroBien obj = new AñadirRegistroBien();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int filaVisual = TablaBien.getSelectedRow();  // Fila seleccionada en la vista

        if (filaVisual == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un Bien.");
            return;
        }

        // Convertimos la fila visual a la del modelo, por si hay filtros/ordenamientos
        int filaModelo = TablaBien.convertRowIndexToModel(filaVisual);

        // Obtenemos el objeto DTO desde la lista
        BienDTO BienSeleccionada = listaFiltradaBien.get(filaModelo);
        ModificarBien obj = new ModificarBien(BienSeleccionada);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        PanelInicio obj = new PanelInicio();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    private List<Object[]> convertirTablaLista() {
        List<Object[]> datosFiltrados = new ArrayList<>();

        if (TablaBien == null) {
            System.out.println("Tabla nula");
            return datosFiltrados;
        }

        TableModel modelo = TablaBien.getModel();
        int columnas = modelo.getColumnCount();

        // agregar encabezado a los datos
        String[] encabezado = new String[columnas];
        for (int i = 0; i < columnas; i++) {
            encabezado[i] = modelo.getColumnName(i);
        }
        datosFiltrados.add(encabezado); //agregamos el encabezado a los datos

        for (int i = 0; i < TablaBien.getRowCount(); i++) {
            int modelIndex = TablaBien.convertRowIndexToModel(i);
            Object[] fila = new Object[columnas];
            for (int j = 0; j < columnas; j++) {
                Object valor = modelo.getValueAt(modelIndex, j);
                fila[j] = (valor != null) ? valor : "";  // evitar null
            }
            datosFiltrados.add(fila);
        }

        return datosFiltrados;
    }


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        List<Object[]> datos = convertirTablaLista();
        exportar obj = new exportar(datos,this);
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    private void cargarBien() {
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{
            "Código","Nombre","Descripción","Categoría","Estado",
            "Responsable a cargo","Inmueble","Ambiente","Fecha Registro"
        }, 0
    );
    listaFiltradaBien = new ArrayList<>(listabien); 
    for (BienDTO bien : listabien) {
        // nombre del inmueble (o vacío si no existe)
        String nombreInmueble = "";
        if (bien.getAmbienteDTO() != null 
            && bien.getAmbienteDTO().getInmuebleDTO() != null) {
            nombreInmueble = bien.getAmbienteDTO()
                                 .getInmuebleDTO()
                                 .getNombre(); 
        }

        modelo.addRow(new Object[]{
            bien.getCodigo(),                           // columna 0: Código
            bien.getNombre(),                           // 1
            bien.getDescripcion(),                      // 2
            bien.getCategoriaDTO()    != null 
                ? bien.getCategoriaDTO().getNombre()    // 3
                : "",
            bien.getEstado_actualDTO() != null 
                ? bien.getEstado_actualDTO().getTipo()  // 4
                : "",
            bien.getResponsableDTO()   != null 
                ? bien.getResponsableDTO().getNombre()  // 5
                : "",
            nombreInmueble,                             // 6: Inmueble
            (bien.getAmbienteDTO() != null 
                ? bien.getAmbienteDTO().getNombre() 
                : ""),                                  // 7: Ambiente
            bien.getFecha_registro()                    // 8
        });
    }

    // 3) Asignamos el modelo actualizado a la tabla
    TablaBien.setModel(modelo);
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BienesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BienesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BienesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BienesPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BienesPrincipal().setVisible(true);
            }
        });
    }

    private void aplicarFiltros() {
    // Lectura de los textos de filtro
    String txtCodigo = jTextField2.getText().trim().toLowerCase();
    String txtNombre = jTextField1.getText().trim().toLowerCase();
    String txtResp   = jTextField6.getText().trim().toLowerCase();
    String txtFecha  = jTextField8.getText().trim();

    // Lectura de los combos (suponiendo que el índice 0 es "Todos" con id = 0)
    CategoriaDTO catSel  = (CategoriaDTO) jComboBox4.getSelectedItem();
    EstadoDTO   estSel  = (EstadoDTO)   jComboBox1.getSelectedItem();
    AmbienteDTO ambSel  = (AmbienteDTO) jComboBox2.getSelectedItem();
    InmuebleDTO inmSel  = (InmuebleDTO) jComboBox3.getSelectedItem();

    int catId = (catSel   != null ? catSel.getId()   : 0);
    int estId = (estSel   != null ? estSel.getId()   : 0);
    int ambId = (ambSel   != null ? ambSel.getId()   : 0);
    int inmId = (inmSel   != null ? inmSel.getId()   : 0);

    // Preparamos el modelo de la tabla
    DefaultTableModel model = new DefaultTableModel(
        new String[]{
            "Código",
            "Nombre",
            "Descripción",
            "Categoría",
            "Estado",
            "Responsable",
            "Inmueble",
            "Ambiente",
            "Fecha Registro"
        },
        0
    );
    listaFiltradaBien.clear();
    // Recorremos todos los bienes y aplicamos cada filtro
    for (BienDTO b : listabien) {
        // 1) Filtrar por codigo
        if (!txtCodigo.isEmpty() &&
            !b.getCodigo().toLowerCase().contains(txtCodigo)) {
            continue;
        }
        
        // 2) Filtrar por nombre
        if (!txtNombre.isEmpty() &&
            !b.getNombre().toLowerCase().contains(txtNombre)) {
            continue;
        }

        // 3) Filtrar por fecha (comparación por contains; adapta si quieres Date)
        if (!txtFecha.isEmpty() &&
            !b.getFecha_registro().toString().contains(txtFecha)) {
            continue;
        }

        // 4) Filtrar por categoría
        if (catId != 0 &&
            (b.getCategoriaDTO() == null || b.getCategoriaDTO().getId() != catId)) {
            continue;
        }

        // 5) Filtrar por estado
        if (estId != 0 &&
            (b.getEstado_actualDTO() == null || b.getEstado_actualDTO().getId() != estId)) {
            continue;
        }

        // 6) Filtrar por responsable
        if (!txtResp.isEmpty() &&
            (b.getResponsableDTO() == null ||
             !b.getResponsableDTO().getNombre().toLowerCase().contains(txtResp))) {
            continue;
        }

        // 7) Filtrar por ambiente
        if (ambId != 0 &&
            (b.getAmbienteDTO() == null || b.getAmbienteDTO().getId() != ambId)) {
            continue;
        }

        // 8) Filtrar por inmueble
        if (inmId != 0 &&
            (b.getAmbienteDTO() == null
             || b.getAmbienteDTO().getInmuebleDTO() == null
             || b.getAmbienteDTO().getInmuebleDTO().getId() != inmId)) {
            continue;
        }

        // A estas alturas, el bien pasa todos los filtros → lo agregamos
        // Primero obtenemos con seguridad los nombres de inmueble y ambiente
        String nombreInmueble = "";
        if (b.getAmbienteDTO() != null && b.getAmbienteDTO().getInmuebleDTO() != null) {
            nombreInmueble = b.getAmbienteDTO().getInmuebleDTO().getNombre();
        }

        String nombreAmbiente = "";
        if (b.getAmbienteDTO() != null) {
            nombreAmbiente = b.getAmbienteDTO().getNombre();
        }

        // Agregamos la fila al modelo
        model.addRow(new Object[]{
            b.getCodigo(),
            b.getNombre(),
            b.getDescripcion(),
            (b.getCategoriaDTO()    != null ? b.getCategoriaDTO().getNombre() : ""),
            (b.getEstado_actualDTO() != null ? b.getEstado_actualDTO().getTipo() : ""),
            (b.getResponsableDTO()   != null ? b.getResponsableDTO().getNombre() : ""),
            nombreInmueble,
            nombreAmbiente,
            b.getFecha_registro()
        });
        listaFiltradaBien.add(b);
    }

    // Asignamos el modelo resultante a la tabla
    TablaBien.setModel(model);
}

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTable TablaBien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<EstadoDTO> jComboBox1;
    private javax.swing.JComboBox<AmbienteDTO> jComboBox2;
    private javax.swing.JComboBox<InmuebleDTO> jComboBox3;
    private javax.swing.JComboBox<CategoriaDTO> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
