/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MOVIMIENTOS;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.contenido.PANEL_INICIO.PanelInicio;
import org.contenido.controlador.Controlador;
import org.contenido.controlador.controladorImpl.BienControlador;
import org.contenido.dto.BienDTO;

/**
 *
 * @author renzo
 */
public class PanelMovimientos extends javax.swing.JFrame {

    /**
     * Creates new form PanelMovimientos
     */
    Controlador<BienDTO> controlador = new BienControlador();
    List<BienDTO> listabien = controlador.listarTodo();
    private List<BienDTO> listaFiltrada = new ArrayList<>(); // NUEVA LÍNEA
    
    public PanelMovimientos() {
        initComponents();
        cargarBien();
        jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        public void insertUpdate(javax.swing.event.DocumentEvent e) { filtrarPorCodigo(); }
        public void removeUpdate(javax.swing.event.DocumentEvent e) { filtrarPorCodigo(); }
        public void changedUpdate(javax.swing.event.DocumentEvent e) { filtrarPorCodigo(); }
    });
    }
    
    private void filtrarPorCodigo() {
        String texto = jTextField1.getText().trim().toLowerCase();

        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{
                "Código", "Nombre", "Descripcion", "Categoria",
                "Estado", "Responsable a cargo", "Ambiente", "Fecha Registro"
            }, 0
        );

        listaFiltrada.clear(); // limpiamos lo anterior

        for (BienDTO bien : listabien) {
            String codigo = bien.getCodigo() != null ? bien.getCodigo().toLowerCase() : "";

            if (texto.isEmpty() || codigo.contains(texto)) {
                listaFiltrada.add(bien); // mantenemos la lista filtrada sincronizada

                modelo.addRow(new Object[]{
                    bien.getCodigo(),
                    bien.getNombre(),
                    bien.getDescripcion(),
                    bien.getCategoriaDTO().getNombre(),
                    bien.getEstado_actualDTO().getTipo(),
                    bien.getResponsableDTO().getNombre(),
                    bien.getAmbienteDTO().getNombre(),
                    bien.getFecha_registro()
                });
            }
        }

        tabla_bien.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rotacion_bien = new javax.swing.JButton();
        asignacion_bien = new javax.swing.JButton();
        estado_bien = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_bien = new org.jdesktop.swingx.JXTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reservaTitulo.png"))); // NOI18N
        jLabel1.setText("Gestión de Movimientos");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel4.setText("Visualiza y gestiona todos lo movientos administrativos de tus bienes");

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        rotacion_bien.setBackground(new java.awt.Color(102, 102, 102));
        rotacion_bien.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        rotacion_bien.setForeground(new java.awt.Color(255, 255, 255));
        rotacion_bien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cadena-de-suministro.png"))); // NOI18N
        rotacion_bien.setText("Rotación");
        rotacion_bien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotacion_bienActionPerformed(evt);
            }
        });

        asignacion_bien.setBackground(new java.awt.Color(255, 102, 0));
        asignacion_bien.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        asignacion_bien.setForeground(new java.awt.Color(255, 255, 255));
        asignacion_bien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/casilla-de-verificacion.png"))); // NOI18N
        asignacion_bien.setText("Asignación");
        asignacion_bien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignacion_bienActionPerformed(evt);
            }
        });

        estado_bien.setBackground(new java.awt.Color(0, 0, 0));
        estado_bien.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        estado_bien.setForeground(new java.awt.Color(255, 255, 255));
        estado_bien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-tareas-16.png"))); // NOI18N
        estado_bien.setText("Estado");
        estado_bien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado_bienActionPerformed(evt);
            }
        });

        tabla_bien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Descripción", "Categoría", "Estado", "Responsable a cargo", "Ambiente", "Fecha de Registro"
            }
        ));
        jScrollPane2.setViewportView(tabla_bien);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jLabel10.setText("Buscar por código de Bien:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asignacion_bien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(rotacion_bien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estado_bien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(asignacion_bien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rotacion_bien, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(estado_bien, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PanelInicio obj = new PanelInicio();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rotacion_bienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotacion_bienActionPerformed
                // TODO add your handling code here:
        int filaVisual = tabla_bien.getSelectedRow();
        if (filaVisual == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un bien.");
            return;
        }

        BienDTO BienSeleccionada = listaFiltrada.get(filaVisual); // USAMOS listaFiltrada

        Tabla_Rotacion obj = new Tabla_Rotacion(BienSeleccionada);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_rotacion_bienActionPerformed

    private void asignacion_bienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignacion_bienActionPerformed
        // TODO add your handling code here:
        int filaVisual = tabla_bien.getSelectedRow();
        if (filaVisual == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un bien.");
            return;
        }

        BienDTO BienSeleccionada = listaFiltrada.get(filaVisual); // USAMOS listaFiltrada

        ModuloAsignacion obj = new ModuloAsignacion(BienSeleccionada);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_asignacion_bienActionPerformed

    private void estado_bienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado_bienActionPerformed
        int filaVisual = tabla_bien.getSelectedRow();
        if (filaVisual == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un bien.");
            return;
        }

        BienDTO BienSeleccionada = listaFiltrada.get(filaVisual); // USAMOS listaFiltrada

        HistorialEstado obj = new HistorialEstado(BienSeleccionada);
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_estado_bienActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void cargarBien(){
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"Código","Nombre","Descripcion", "Categoria","Estado","Responsable a cargo","Ambiente","Fecha Registro"}, 0
        );

        listaFiltrada.clear(); // NUEVO: sincronizar lista filtrada desde el inicio

        for (BienDTO bien : listabien) {
            listaFiltrada.add(bien); // NUEVO: copiar los datos iniciales

            modelo.addRow(new Object[]{
                bien.getCodigo(),
                bien.getNombre(),
                bien.getDescripcion(),
                bien.getCategoriaDTO().getNombre(),
                bien.getEstado_actualDTO().getTipo(),
                bien.getResponsableDTO().getNombre(),
                bien.getAmbienteDTO().getNombre(),
                bien.getFecha_registro(),
            });
        }

        tabla_bien.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelMovimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignacion_bien;
    private javax.swing.JButton estado_bien;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton rotacion_bien;
    private org.jdesktop.swingx.JXTable tabla_bien;
    // End of variables declaration//GEN-END:variables
}
